baseURL = "https://julienchastang.com"
languageCode = "en-us"
title = "julienchastang"
theme = "hugo-classic"

pygmentsCodeFences = true
PygmentsStyle = "emacs"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.feed]]
    name = "rss"
    url = "/index.xml"
[params]
    description = "Julien Chastang's Home on the Web"
    footer = "[GitHub](https://github.com/julienchastang) | [.emacs](https://github.com/julienchastang/dotemacs) | [LinkedIn](https://www.linkedin.com/in/julienchastang) | [Twitter](https://twitter.com/JulienChastang) | [Source](https://github.com/julienchastang/julienchastang.com)"
